import type { GlossaryTerm } from "./types";

export const glossary: GlossaryTerm[] = [
  {
    id: "g-proue",
    terme: "Proue",
    definition: "L'avant du bateau.",
    categorie: "Bateau",
    termesAssociesIds: ["g-poupe", "g-etrave"],
    lessonId: "l1-parties-du-bateau",
  },
  {
    id: "g-poupe",
    terme: "Poupe",
    definition: "L'arrière du bateau.",
    categorie: "Bateau",
    termesAssociesIds: ["g-proue"],
    lessonId: "l1-parties-du-bateau",
  },
  {
    id: "g-etrave",
    terme: "Étrave",
    definition: "La pièce avant de la coque, à la pointe de la proue, qui fend l'eau.",
    categorie: "Bateau",
    termesAssociesIds: ["g-proue"],
  },
  {
    id: "g-coque",
    terme: "Coque",
    definition: "La structure flottante du bateau, immergée (carène) et émergée (œuvres mortes).",
    categorie: "Bateau",
    termesAssociesIds: ["g-quille", "g-derive"],
    lessonId: "l1-parties-du-bateau",
  },
  {
    id: "g-pont",
    terme: "Pont",
    definition: "La surface horizontale supérieure du bateau, sur laquelle on se déplace.",
    categorie: "Bateau",
    termesAssociesIds: ["g-cockpit"],
    lessonId: "l1-parties-du-bateau",
  },
  {
    id: "g-mat",
    terme: "Mât",
    definition: "Le grand espar vertical qui porte les voiles.",
    categorie: "Bateau",
    termesAssociesIds: ["g-bome", "g-haubans", "g-etai"],
    lessonId: "l1-parties-du-bateau",
  },
  {
    id: "g-bome",
    terme: "Bôme",
    definition: "L'espar horizontal fixé au bas du mât, qui tient la bordure de la grand-voile.",
    categorie: "Bateau",
    termesAssociesIds: ["g-mat", "g-grand-voile"],
    lessonId: "l1-parties-du-bateau",
  },
  {
    id: "g-cockpit",
    terme: "Cockpit",
    definition: "L'espace, généralement à l'arrière, où l'équipage barre et manœuvre les cordages.",
    categorie: "Bateau",
    termesAssociesIds: ["g-barre", "g-winch"],
    lessonId: "l1-parties-du-bateau",
  },
  {
    id: "g-quille",
    terme: "Quille",
    definition: "Appendice fixe et lesté sous la coque, qui limite la dérive latérale et stabilise le bateau.",
    categorie: "Bateau",
    termesAssociesIds: ["g-derive", "g-gite"],
  },
  {
    id: "g-derive",
    terme: "Dérive",
    definition: "1) Appendice mobile qui joue le même rôle qu'une quille sur les petits bateaux. 2) Écart entre le cap suivi et la route réellement parcourue, sous l'effet du vent ou du courant.",
    categorie: "Bateau",
    termesAssociesIds: ["g-quille", "g-cap"],
  },
  {
    id: "g-etai",
    terme: "Étai",
    definition: "Câble qui va du mât vers l'avant du bateau et maintient le mât ; le génois ou foc y est souvent fixé.",
    categorie: "Bateau",
    termesAssociesIds: ["g-mat", "g-foc", "g-haubans"],
  },
  {
    id: "g-haubans",
    terme: "Haubans",
    definition: "Câbles qui maintiennent le mât latéralement, de chaque côté du bateau.",
    categorie: "Bateau",
    termesAssociesIds: ["g-mat", "g-etai"],
  },
  {
    id: "g-gite",
    terme: "Gîte",
    definition: "Inclinaison latérale du bateau sous l'effet du vent dans les voiles.",
    categorie: "Bateau",
    termesAssociesIds: ["g-quille"],
    lessonId: "l1-vocabulaire-essentiel",
  },
  {
    id: "g-cap",
    terme: "Cap",
    definition: "Direction visée par le bateau, exprimée en degrés (0° au nord, 90° à l'est, etc.).",
    categorie: "Navigation",
    termesAssociesIds: ["g-derive"],
    lessonId: "l1-vocabulaire-essentiel",
  },
  {
    id: "g-equipage",
    terme: "Équipage",
    definition: "Ensemble des personnes présentes à bord pour faire naviguer le bateau.",
    categorie: "Bateau",
    termesAssociesIds: [],
    lessonId: "l1-vocabulaire-essentiel",
  },
  {
    id: "g-mouiller",
    terme: "Mouiller",
    definition: "Jeter l'ancre pour immobiliser le bateau.",
    categorie: "Manœuvres",
    termesAssociesIds: [],
    lessonId: "l1-vocabulaire-essentiel",
  },
  {
    id: "g-vent-reel",
    terme: "Vent réel",
    definition: "Le vent tel que le mesurerait un observateur fixe, immobile par rapport à l'eau.",
    categorie: "Vent",
    termesAssociesIds: ["g-vent-apparent"],
    lessonId: "l1-le-vent",
  },
  {
    id: "g-vent-apparent",
    terme: "Vent apparent (apparent wind)",
    definition: "Le vent réellement ressenti à bord : la combinaison du vent réel et du vent créé par le déplacement du bateau.",
    categorie: "Vent",
    termesAssociesIds: ["g-vent-reel"],
    lessonId: "l1-le-vent",
  },
  {
    id: "g-tribord",
    terme: "Tribord",
    definition: "Le côté droit du bateau, quand on regarde vers l'avant. Signalé de nuit par un feu vert.",
    categorie: "Bateau",
    termesAssociesIds: ["g-babord"],
    lessonId: "l1-tribord-babord",
  },
  {
    id: "g-babord",
    terme: "Bâbord",
    definition: "Le côté gauche du bateau, quand on regarde vers l'avant. Signalé de nuit par un feu rouge.",
    categorie: "Bateau",
    termesAssociesIds: ["g-tribord"],
    lessonId: "l1-tribord-babord",
  },
  {
    id: "g-travers",
    terme: "Travers",
    definition: "Direction perpendiculaire (90°) à l'axe du bateau.",
    categorie: "Navigation",
    termesAssociesIds: ["g-tribord", "g-babord"],
    lessonId: "l1-avant-arriere",
  },
  {
    id: "g-amure",
    terme: "Amure",
    definition: "Le côté du bateau d'où vient le vent. « Tribord amure » : le vent vient de tribord.",
    categorie: "Vent",
    termesAssociesIds: ["g-tribord", "g-babord"],
    lessonId: "l1-amure",
  },
  {
    id: "g-pres",
    terme: "Près",
    definition: "Allure la plus proche possible du vent, juste avant le lit du vent.",
    categorie: "Vent",
    termesAssociesIds: ["g-largue", "g-vent-arriere"],
    lessonId: "l1-les-allures",
  },
  {
    id: "g-largue",
    terme: "Largue",
    definition: "Allure entre le travers et le vent arrière, où le vent vient de l'arrière du travers.",
    categorie: "Vent",
    termesAssociesIds: ["g-pres", "g-vent-arriere"],
    lessonId: "l1-les-allures",
  },
  {
    id: "g-vent-arriere",
    terme: "Vent arrière (running)",
    definition: "Allure où le vent pousse le bateau directement par l'arrière.",
    categorie: "Vent",
    termesAssociesIds: ["g-pres", "g-largue"],
    lessonId: "l1-les-allures",
  },
  {
    id: "g-grand-voile",
    terme: "Grand-voile (mainsail)",
    definition: "Voile principale, hissée le long du mât et tenue en bas par la bôme.",
    categorie: "Voiles",
    termesAssociesIds: ["g-foc", "g-spi", "g-bome"],
    lessonId: "l1-les-voiles",
  },
  {
    id: "g-foc",
    terme: "Génois / foc (genoa / jib)",
    definition: "Voile d'avant, fixée sur l'étai. Le génois — la voile d'avant par défaut sur la plupart des voiliers — est plus grand et recouvre en partie la grand-voile ; le foc est plus petit.",
    categorie: "Voiles",
    termesAssociesIds: ["g-grand-voile", "g-etai"],
    lessonId: "l1-les-voiles",
  },
  {
    id: "g-spi",
    terme: "Spinnaker (spi)",
    definition: "Voile ample et légère utilisée aux allures portantes (grand largue, vent arrière) pour capter un maximum de vent.",
    categorie: "Voiles",
    termesAssociesIds: ["g-grand-voile", "g-foc"],
    lessonId: "l1-les-voiles",
  },
  {
    id: "g-ecoute",
    terme: "Écoute (sheet)",
    definition: "Cordage qui règle l'angle d'une voile par rapport au vent : on la borde (tire) ou on la choque (relâche).",
    categorie: "Cordages",
    termesAssociesIds: ["g-drisse", "g-winch"],
    lessonId: "l2-ecoutes-et-drisses",
  },
  {
    id: "g-faseillement",
    terme: "Faseillement (luffing)",
    definition: "Battement d'une voile pas assez bordée : le bord d'attaque flotte et claque, la voile perd sa forme et ne porte plus.",
    categorie: "Voiles",
    termesAssociesIds: ["g-ecoute", "g-penon"],
    lessonId: "l-regler-les-voiles",
  },
  {
    id: "g-penon",
    terme: "Penon (telltale)",
    definition: "Petit ruban fixé sur une voile qui indique visuellement si l'écoulement de l'air est correct : s'il décroche d'un côté, la voile n'est pas encore bien réglée.",
    categorie: "Voiles",
    termesAssociesIds: ["g-faseillement", "g-ecoute"],
    lessonId: "l-regler-les-voiles",
  },
  {
    id: "g-drisse",
    terme: "Drisse (halyard)",
    definition: "Cordage utilisé pour hisser une voile le long du mât ou de l'étai.",
    categorie: "Cordages",
    termesAssociesIds: ["g-ecoute"],
    lessonId: "l2-ecoutes-et-drisses",
  },
  {
    id: "g-winch",
    terme: "Winch",
    definition: "Treuil manuel qui démultiplie la force nécessaire pour border un cordage sous tension.",
    categorie: "Cordages",
    termesAssociesIds: ["g-ecoute", "g-drisse"],
    lessonId: "l2-le-winch",
  },
  {
    id: "g-barre",
    terme: "Barre",
    definition: "Commande (barre franche ou roue) qui actionne le safran pour diriger le bateau.",
    categorie: "Bateau",
    termesAssociesIds: ["g-safran"],
    lessonId: "l2-barre-et-safran",
  },
  {
    id: "g-safran",
    terme: "Safran",
    definition: "Surface immergée à l'arrière du bateau qui, orientée par la barre, fait tourner le bateau.",
    categorie: "Bateau",
    termesAssociesIds: ["g-barre"],
    lessonId: "l2-barre-et-safran",
  },
  {
    id: "g-empannage",
    terme: "Empannage (gybe)",
    definition: "Manœuvre qui consiste à changer d'amure en passant par le vent arrière.",
    categorie: "Manœuvres",
    termesAssociesIds: ["g-virement", "g-amure"],
    lessonId: "l3-empannage",
  },
  {
    id: "g-virement",
    terme: "Virement de bord (tack)",
    definition: "Manœuvre qui consiste à changer d'amure en passant par le lit du vent (face au vent).",
    categorie: "Manœuvres",
    termesAssociesIds: ["g-empannage", "g-amure"],
    lessonId: "l3-virement-de-bord",
  },
  {
    id: "g-ris",
    terme: "Ris",
    definition: "Réduction de la surface de la grand-voile, en la repliant partiellement, pour naviguer par vent fort.",
    categorie: "Manœuvres",
    termesAssociesIds: ["g-grand-voile"],
    lessonId: "l3-reduire-la-toile",
  },
  {
    id: "g-vhf",
    terme: "VHF",
    definition: "Radio marine à très haute fréquence, utilisée pour communiquer et lancer un appel de détresse en mer.",
    categorie: "Sécurité",
    termesAssociesIds: ["g-mayday", "g-panpan"],
    lessonId: "l6-alerte-vhf",
  },
  {
    id: "g-mayday",
    terme: "Mayday",
    definition: "Signal international de détresse par radio (VHF), utilisé uniquement en cas de danger grave et imminent pour la vie ou le bateau.",
    categorie: "Sécurité",
    termesAssociesIds: ["g-vhf", "g-panpan"],
    lessonId: "l6-alerte-vhf",
  },
  {
    id: "g-panpan",
    terme: "Pan-pan",
    definition: "Signal d'urgence par radio (VHF), pour une situation urgente mais qui ne met pas immédiatement en jeu la vie ou le bateau.",
    categorie: "Sécurité",
    termesAssociesIds: ["g-vhf", "g-mayday"],
    lessonId: "l6-alerte-vhf",
  },
  {
    id: "g-homme-a-la-mer",
    terme: "Homme à la mer",
    definition: "Situation d'urgence où une personne tombe à l'eau ; déclenche une procédure de récupération immédiate.",
    categorie: "Sécurité",
    termesAssociesIds: ["g-gilet"],
    lessonId: "l6-homme-a-la-mer",
  },
  {
    id: "g-gilet",
    terme: "Gilet de sauvetage",
    definition: "Équipement de sécurité individuel obligatoire à bord, à porter selon les conditions et la réglementation en vigueur.",
    categorie: "Sécurité",
    termesAssociesIds: ["g-homme-a-la-mer"],
    lessonId: "l6-equipement-de-securite",
  },
  {
    id: "g-carte-marine",
    terme: "Carte marine",
    definition: "Carte représentant les profondeurs, la côte, les dangers et les aides à la navigation, indispensable pour se repérer en mer.",
    categorie: "Navigation",
    termesAssociesIds: ["g-cap"],
    lessonId: "l4-lire-une-carte",
  },
  {
    id: "g-balisage-laterale",
    terme: "Balisage latéral",
    definition: "Marques colorées (rouges et vertes) qui signalent les limites d'un chenal, à laisser d'un côté ou de l'autre selon le sens de navigation.",
    categorie: "Navigation",
    termesAssociesIds: ["g-tribord", "g-babord"],
    lessonId: "l4-balisage",
  },
  {
    id: "g-maree-courant",
    terme: "Marée et courant",
    definition: "La marée fait varier la hauteur d'eau et génère des courants qui peuvent faire dériver un bateau ou influencer un mouillage.",
    categorie: "Navigation",
    termesAssociesIds: ["g-derive"],
    lessonId: "l4-mouillage",
  },
  {
    id: "g-marnage",
    terme: "Marnage",
    definition: "Différence de hauteur d'eau entre une pleine mer et la basse mer qui la suit (ou la précède). Le coefficient de marée, publié chaque jour, indique l'amplitude de la marée du moment sur une échelle de 20 à 120, indépendamment du marnage local en mètres.",
    categorie: "Navigation",
    termesAssociesIds: ["g-maree-courant"],
    lessonId: "l4-marnage-coefficient",
  },
  {
    id: "g-regle-douziemes",
    terme: "Règle des douzièmes",
    definition: "Méthode qui approxime la montée ou la descente de l'eau entre deux marées par paliers horaires (1/12, 2/12, 3/12, 3/12, 2/12, 1/12 du marnage, heure par heure) : l'eau bouge lentement au début et à la fin, vite au milieu.",
    categorie: "Navigation",
    termesAssociesIds: ["g-marnage"],
    lessonId: "l4-regle-douziemes",
  },
  {
    id: "g-flot",
    terme: "Flot",
    definition: "Courant de marée montante, qui porte généralement vers la côte.",
    categorie: "Navigation",
    termesAssociesIds: ["g-jusant", "g-etale"],
    lessonId: "l4-courants-de-maree",
  },
  {
    id: "g-jusant",
    terme: "Jusant",
    definition: "Courant de marée descendante, qui porte généralement vers le large.",
    categorie: "Navigation",
    termesAssociesIds: ["g-flot", "g-etale"],
    lessonId: "l4-courants-de-maree",
  },
  {
    id: "g-etale",
    terme: "Étale",
    definition: "Bref moment, au changement de sens du courant, où celui-ci s'annule presque entre le flot et le jusant. Dans certains passages resserrés, ce moment ne dure que quelques minutes.",
    categorie: "Navigation",
    termesAssociesIds: ["g-flot", "g-jusant"],
    lessonId: "l4-courants-de-maree",
  },
  {
    id: "g-beaufort",
    terme: "Échelle de Beaufort",
    definition: "Échelle qui classe la force du vent de 0 (calme plat) à 12 (ouragan), à partir de l'observation de l'état de la mer.",
    categorie: "Météo",
    termesAssociesIds: [],
    lessonId: "l5-echelle-de-beaufort",
  },
  {
    id: "g-feux-navigation",
    terme: "Feux de navigation",
    definition: "Feux réglementaires (vert à tribord, rouge à bâbord, blancs à l'avant et à l'arrière) qui signalent de nuit la direction d'un bateau.",
    categorie: "Sécurité",
    termesAssociesIds: ["g-tribord", "g-babord"],
    lessonId: "l7-feux-de-navigation",
  },
];

export function getGlossaryTerm(id: string): GlossaryTerm | undefined {
  return glossary.find((g) => g.id === id);
}

export function searchGlossary(query: string): GlossaryTerm[] {
  const q = query.trim().toLowerCase();
  if (!q) return glossary;
  return glossary.filter(
    (g) => g.terme.toLowerCase().includes(q) || g.definition.toLowerCase().includes(q)
  );
}
