import type { QuizItem } from "./types";

export const quizItems: QuizItem[] = [
  {
    id: "qz-parties-poupe",
    type: "qcm",
    conceptIds: ["c-poupe", "c-proue"],
    enonce: "Quelle partie du bateau se trouve à l'opposé de la proue ?",
    options: ["Le cockpit", "La poupe", "Le pont", "La bôme"],
    reponseIndex: 1,
    explication: "La poupe est l'arrière du bateau, à l'opposé de la proue (l'avant).",
  },
  {
    id: "qz-babord-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-babord"],
    enonce: "Bâbord est toujours le côté gauche du bateau, quel que soit l'endroit où l'on se trouve à bord.",
    reponse: true,
    explication: "Contrairement à « gauche » et « droite », bâbord et tribord ne dépendent pas de l'orientation de la personne : ils désignent toujours le même côté du bateau.",
  },
  {
    id: "qz-vent-apparent",
    type: "qcm",
    conceptIds: ["c-vent-apparent", "c-vent-reel"],
    enonce: "Qu'est-ce que le vent apparent ?",
    options: [
      "Le vent mesuré par la météo avant de partir",
      "Le vent réellement ressenti à bord, combinaison du vent réel et du déplacement du bateau",
      "Un synonyme du vent réel",
      "Le vent uniquement présent au près",
    ],
    reponseIndex: 1,
    explication: "Le vent apparent est ce que l'équipage ressent réellement : il dépend à la fois du vent réel et de la vitesse/direction du bateau.",
  },
  {
    id: "qz-amure-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-amure-tribord", "c-amure-babord"],
    enonce: "L'amure d'un bateau indique la voile qui est actuellement hissée.",
    reponse: false,
    explication: "L'amure indique le côté du bateau d'où vient le vent (tribord amure ou bâbord amure), pas la voile utilisée.",
  },
  {
    id: "qz-allures-association",
    type: "association",
    conceptIds: [
      "c-allure-pres",
      "c-allure-travers",
      "c-allure-vent-arriere",
    ],
    enonce: "Associe chaque allure à sa description.",
    paires: [
      { gauche: "Le près", droite: "Au plus proche du vent, juste avant le lit du vent" },
      { gauche: "Le travers", droite: "Le vent arrive à 90° du bateau" },
      { gauche: "Le vent arrière", droite: "Le vent pousse directement par l'arrière" },
    ],
    explication: "L'allure se définit uniquement par l'angle entre le cap du bateau et la direction du vent réel.",
  },
  {
    id: "qz-cordages-association",
    type: "association",
    conceptIds: ["c-ecoute", "c-drisse", "c-winch"],
    enonce: "Associe chaque élément à sa fonction.",
    paires: [
      { gauche: "La drisse", droite: "Hisse une voile" },
      { gauche: "L'écoute", droite: "Règle l'angle d'une voile déjà hissée" },
      { gauche: "Le winch", droite: "Démultiplie la force pour border un cordage" },
    ],
    explication: "Trois éléments, trois rôles bien distincts — indispensables pour comprendre une consigne à bord.",
  },
  {
    id: "qz-reconnaissance-allure",
    type: "reconnaissance",
    conceptIds: ["c-allure-travers"],
    enonce: "Regarde le schéma : quelle allure ce bateau adopte-t-il ?",
    illustration: "quiz-point-of-sail-beam",
    options: ["Le près", "Le travers", "Le grand largue", "Le vent arrière"],
    reponseIndex: 1,
    explication: "La flèche de vent arrive perpendiculairement à l'axe du bateau : c'est l'allure du travers.",
  },
  {
    id: "qz-reconnaissance-partie",
    type: "reconnaissance",
    conceptIds: ["c-bome"],
    enonce: "Sur ce schéma, quelle est la pièce mise en évidence ?",
    illustration: "quiz-boat-part-boom",
    options: ["Le mât", "La bôme", "Le safran", "L'étai"],
    reponseIndex: 1,
    explication: "C'est la bôme : l'espar horizontal qui tient le bas de la grand-voile.",
  },
  {
    id: "qz-scenario-vent-forcit",
    type: "scenario",
    conceptIds: ["c-vent-force", "c-reduire-toile"],
    situation:
      "Tu navigues au près. Le vent forcit rapidement. Le bateau gîte beaucoup et devient difficile à contrôler.",
    options: [
      "Augmenter la surface de voile",
      "Prendre un ris pour réduire la toile",
      "Empanner",
      "Affaler immédiatement toutes les voiles",
    ],
    reponseIndex: 1,
    explication:
      "Quand le vent forcit, réduire la toile (prendre un ris) permet de garder un bateau plus équilibré et contrôlable, sans pour autant tout affaler et perdre la propulsion.",
    chronometre: true,
  },
  {
    id: "qz-scenario-priorite-amures",
    type: "scenario",
    conceptIds: ["c-priorite-amures", "c-amure-tribord", "c-amure-babord"],
    situation: "Tu navigues tribord amure. Un autre voilier arrive et navigue bâbord amure. Vos routes se croisent.",
    options: [
      "C'est à toi de t'écarter",
      "C'est à l'autre voilier de s'écarter",
      "Le plus rapide des deux a la priorité",
      "Chacun garde son cap, il n'y a pas de règle",
    ],
    reponseIndex: 1,
    explication:
      "Règle officielle (RIPAM / COLERG, règle 12) : entre deux voiliers, le bateau bâbord amure doit s'écarter du bateau tribord amure. Cette règle est approfondie et nuancée au Niveau 7 — elle ne remplace pas une formation encadrée.",
  },
  {
    id: "qz-travers-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-travers-mot"],
    enonce: "« Par le travers tribord » signifie qu'un objet se trouve droit devant le bateau.",
    reponse: false,
    explication: "Le travers désigne une direction perpendiculaire (90°) à l'axe du bateau, pas devant.",
  },
  {
    id: "qz-lit-du-vent",
    type: "qcm",
    conceptIds: ["c-lit-du-vent"],
    enonce: "Que se passe-t-il si un voilier essaie d'avancer directement dans le lit du vent ?",
    options: [
      "Il avance plus vite qu'au près",
      "Les voiles ne portent pas, le bateau ne peut pas avancer dans cet axe",
      "C'est l'allure du vent arrière",
      "Rien de particulier",
    ],
    reponseIndex: 1,
    explication: "Face au vent, dans le lit du vent, les voiles ne peuvent pas être gonflées : c'est une zone où l'on ne peut pas naviguer directement.",
  },
  {
    id: "qz-gite-qcm",
    type: "qcm",
    conceptIds: ["c-gite"],
    enonce: "Comment s'appelle l'inclinaison latérale du bateau sous l'effet du vent ?",
    options: ["La dérive", "La gîte", "L'abattée", "Le ris"],
    reponseIndex: 1,
    explication: "La gîte est l'inclinaison du bateau causée par la pression du vent dans les voiles.",
  },
  {
    id: "qz-voiles-qcm",
    type: "qcm",
    conceptIds: ["c-spi-notion", "c-foc-notion"],
    enonce: "Le génois se distingue du foc principalement par :",
    options: [
      "Sa couleur",
      "Sa taille : il est plus grand et recouvre en partie la grand-voile",
      "Le fait qu'il ne se hisse pas avec une drisse",
      "Il n'y a aucune différence",
    ],
    reponseIndex: 1,
    explication: "Le génois est une voile d'avant plus grande que le foc, qui recouvre partiellement la grand-voile.",
  },
  {
    id: "qz-barre-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-barre", "c-safran"],
    enonce: "Avec une roue à barre, tourner vers tribord fait tourner le bateau vers tribord.",
    reponse: true,
    explication: "La roue a un sens direct, contrairement à la barre franche dont le mouvement est inversé.",
  },
  {
    id: "qz-virement-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-virement"],
    enonce: "Pendant un virement de bord, le bateau passe par le lit du vent.",
    reponse: true,
    explication: "Le virement change d'amure en passant face au vent, contrairement à l'empannage qui passe par le vent arrière.",
  },
  {
    id: "qz-empannage-securite",
    type: "qcm",
    conceptIds: ["c-empannage"],
    enonce: "Quel geste réduit le risque pendant un empannage ?",
    options: [
      "Border la grand-voile vers l'axe avant de faire passer la bôme",
      "Choquer complètement la grand-voile avant d'empanner",
      "Empanner le plus vite possible",
      "Empanner sans prévenir l'équipage",
    ],
    reponseIndex: 0,
    explication: "Border la grand-voile avant l'empannage limite la course de la bôme quand elle traverse.",
  },
  {
    id: "qz-balisage-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-balisage-laterale"],
    enonce: "En rentrant vers le port en France, une marque latérale rouge se laisse généralement à bâbord.",
    reponse: true,
    explication: "Système IALA région A : en revenant vers le port, les marques rouges se laissent à bâbord, les vertes à tribord.",
  },
  {
    id: "qz-beaufort-qcm",
    type: "qcm",
    conceptIds: ["c-beaufort", "c-vent-force"],
    enonce: "L'échelle de Beaufort permet d'estimer la force du vent principalement à partir de :",
    options: [
      "La lecture d'un anémomètre uniquement",
      "L'observation de l'état de la mer et du vent",
      "La météo du lendemain",
      "La couleur du ciel uniquement",
    ],
    reponseIndex: 1,
    explication: "L'échelle de Beaufort a été conçue pour estimer le vent à partir de ce qu'on observe sur l'eau, sans instrument.",
  },
  {
    id: "qz-homme-a-la-mer-scenario",
    type: "scenario",
    conceptIds: ["c-homme-a-la-mer"],
    situation: "Un équipier tombe à l'eau alors que le bateau navigue au portant.",
    options: [
      "Continuer la route et revenir plus tard",
      "Crier « Homme à la mer », désigner un guetteur qui ne le quitte pas des yeux, et manœuvrer pour revenir",
      "Sauter à l'eau immédiatement sans gilet pour le rejoindre",
      "Attendre qu'il remonte seul à bord",
    ],
    reponseIndex: 1,
    explication:
      "Alerter, désigner un guetteur qui garde la personne en vue en permanence, puis manœuvrer pour revenir : les trois réflexes immédiats.",
    chronometre: true,
  },
  {
    id: "qz-priorite-voilier-moteur",
    type: "vrai-faux",
    conceptIds: ["c-priorite-voilier-moteur"],
    enonce: "Un voilier moteur allumé et embrayé, même voiles hissées, est considéré comme un bateau à moteur pour les règles de priorité.",
    reponse: true,
    explication: "Dès que le moteur propulse le bateau, le voilier perd la priorité qu'il aurait eue à la voile seule.",
  },
  {
    id: "qz-ordre-virement",
    type: "ordre-etapes",
    conceptIds: ["c-virement"],
    titre: "Le virement de bord",
    etapes: [
      "Vérifier que la route est dégagée",
      "Annoncer : « Paré à virer ? / Je vire ! »",
      "Pousser doucement la barre sous le vent",
      "Ouvrir le taquet de l'écoute bordée",
      "Choquer l'écoute à la main, progressivement",
      "Attraper la nouvelle écoute dès que le génois passe de l'autre côté",
      "Border à la main puis terminer au winch",
      "Bloquer l'écoute dans son taquet",
      "Stabiliser le cap sur la nouvelle amure",
    ],
    explication:
      "Barre et écoute s'enchaînent : on tourne le bateau, on relâche l'ancienne écoute au bon moment, on attrape et on borde la nouvelle, puis on stabilise. Se répéter jusqu'à ce que l'ordre devienne un réflexe.",
  },

  // --- Enrichissement : couvrir les notions qui n'avaient encore aucune question ---

  {
    id: "qz-reconnaissance-mat",
    type: "reconnaissance",
    conceptIds: ["c-mat"],
    enonce: "Sur ce schéma, quelle est la pièce mise en évidence ?",
    illustration: "quiz-boat-part-mat",
    options: ["Le mât", "La bôme", "Le safran", "L'étai"],
    reponseIndex: 0,
    explication: "C'est le mât : il porte les voiles et soutient le gréement.",
  },
  {
    id: "qz-reconnaissance-coque",
    type: "reconnaissance",
    conceptIds: ["c-coque"],
    enonce: "Sur ce schéma, quelle est la pièce mise en évidence ?",
    illustration: "quiz-boat-part-coque",
    options: ["Le pont", "La coque", "Le cockpit", "La bôme"],
    reponseIndex: 1,
    explication: "C'est la coque : l'ensemble de la structure flottante du bateau.",
  },
  {
    id: "qz-reconnaissance-pont",
    type: "reconnaissance",
    conceptIds: ["c-pont"],
    enonce: "Sur ce schéma, quelle est la pièce mise en évidence ?",
    illustration: "quiz-boat-part-pont",
    options: ["La coque", "Le cockpit", "Le pont", "Le mât"],
    reponseIndex: 2,
    explication: "C'est le pont : la surface horizontale sur laquelle on se déplace à bord.",
  },
  {
    id: "qz-reconnaissance-cockpit",
    type: "reconnaissance",
    conceptIds: ["c-cockpit"],
    enonce: "Sur ce schéma, quelle est la pièce mise en évidence ?",
    illustration: "quiz-boat-part-cockpit",
    options: ["Le cockpit", "Le pont", "La proue", "La poupe"],
    reponseIndex: 0,
    explication: "C'est le cockpit : l'espace où l'équipage barre et manœuvre.",
  },
  {
    id: "qz-vocabulaire-association",
    type: "association",
    conceptIds: ["c-cap", "c-equipage", "c-mouiller"],
    enonce: "Associe chaque mot à sa définition.",
    paires: [
      { gauche: "Le cap", droite: "La direction visée, exprimée en degrés" },
      { gauche: "L'équipage", droite: "L'ensemble des personnes à bord" },
      { gauche: "Mouiller", droite: "Jeter l'ancre pour immobiliser le bateau" },
    ],
    explication: "Trois mots basiques mais qui reviennent à chaque sortie — bien les distinguer évite les malentendus.",
  },
  {
    id: "qz-tribord-feu-qcm",
    type: "qcm",
    conceptIds: ["c-tribord", "c-feux-navigation"],
    enonce: "Quelle couleur de feu de navigation correspond au côté tribord ?",
    options: ["Rouge", "Vert", "Blanc", "Jaune"],
    reponseIndex: 1,
    explication: "Tribord correspond au feu vert, bâbord au feu rouge — une convention qui ne change jamais.",
  },
  {
    id: "qz-avant-arriere-qcm",
    type: "qcm",
    conceptIds: ["c-avant", "c-arriere"],
    enonce: "Comment appelle-t-on la zone proche de la poupe ?",
    options: ["L'avant", "L'arrière", "Le travers", "Le lit du vent"],
    reponseIndex: 1,
    explication: "L'arrière désigne la zone proche de la poupe, comme l'avant désigne celle proche de la proue.",
  },
  {
    id: "qz-reconnaissance-bon-plein",
    type: "reconnaissance",
    conceptIds: ["c-allure-bon-plein"],
    enonce: "Regarde le schéma : quelle allure ce bateau adopte-t-il ?",
    illustration: "quiz-point-of-sail-bon-plein",
    options: ["Le près", "Le bon plein", "Le grand largue", "Le vent arrière"],
    reponseIndex: 1,
    explication: "Un peu plus ouvert que le près : c'est le bon plein, une allure rapide et confortable.",
  },
  {
    id: "qz-reconnaissance-grand-largue",
    type: "reconnaissance",
    conceptIds: ["c-allure-grand-largue"],
    enonce: "Regarde le schéma : quelle allure ce bateau adopte-t-il ?",
    illustration: "quiz-point-of-sail-grand-largue",
    options: ["Le travers", "Le largue", "Le grand largue", "Le vent arrière"],
    reponseIndex: 2,
    explication: "Encore plus ouvert que le largue, presque vent arrière : c'est le grand largue.",
  },
  {
    id: "qz-largue-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-allure-largue"],
    enonce: "Au largue, le vent arrive pile perpendiculairement au bateau.",
    reponse: false,
    explication: "C'est la définition du travers. Au largue, le vent vient de l'arrière du travers, pas pile à 90°.",
  },
  {
    id: "qz-grand-voile-points-qcm",
    type: "qcm",
    conceptIds: ["c-grand-voile-parties"],
    enonce: "Combien de points (coins) compte la grand-voile ?",
    options: ["Deux", "Trois", "Quatre", "Cinq"],
    reponseIndex: 1,
    explication: "Trois points : le point de drisse (en haut), le point d'amure et le point d'écoute (en bas).",
  },
  {
    id: "qz-grand-voile-notion-qcm",
    type: "qcm",
    conceptIds: ["c-grand-voile-notion"],
    enonce: "Quelle voile est hissée le long du mât et de la bôme, et sert de voile principale ?",
    options: ["Le foc", "Le spinnaker", "La grand-voile", "Le génois"],
    reponseIndex: 2,
    explication: "La grand-voile est la voile principale, hissée le long du mât et tenue en bas par la bôme.",
  },
  {
    id: "qz-ordre-noeud-chaise",
    type: "ordre-etapes",
    conceptIds: ["c-noeud-chaise"],
    titre: "Le nœud de chaise",
    etapes: [
      "Former une petite boucle sur le dormant.",
      "Faire passer le courant à travers cette boucle, par en dessous.",
      "Passer le courant autour du dormant.",
      "Repasser le courant dans la boucle initiale, en sens inverse.",
      "Serrer en tenant la boucle finale et en tirant sur le dormant.",
    ],
    explication: "Le nœud de chaise forme une boucle fixe qui ne se resserre jamais sur elle-même — indispensable pour s'attacher en sécurité.",
  },
  {
    id: "qz-faseillement-qcm",
    type: "qcm",
    conceptIds: ["c-faseillement"],
    enonce: "Que se passe-t-il quand une voile n'est pas assez bordée ?",
    options: ["Elle se déchire aussitôt", "Elle faseille : le bord d'attaque flotte et claque", "Elle prend davantage de vitesse", "Rien de visible ne change"],
    reponseIndex: 1,
    explication: "Une voile pas assez bordée faseille : elle perd sa forme et ne porte plus, jusqu'à ce qu'on la borde à nouveau.",
  },
  {
    id: "qz-penon-qcm",
    type: "qcm",
    conceptIds: ["c-penon"],
    enonce: "Un penon flotte du côté sous le vent de la voile. Que dois-tu faire ?",
    options: ["Border davantage", "Choquer un peu", "Ne rien faire, c'est normal", "Changer d'allure"],
    reponseIndex: 1,
    explication: "Un penon qui flotte côté sous le vent signale une voile trop bordée : il faut choquer, pas border.",
  },
  {
    id: "qz-ordre-prise-de-ris",
    type: "ordre-etapes",
    conceptIds: ["c-prise-de-ris"],
    titre: "Prendre un ris",
    etapes: [
      "Mettre le bateau au près serré ou face au vent, pour dépowerer la grand-voile.",
      "Choquer complètement l'écoute de grand-voile.",
      "Choquer la drisse en l'accompagnant à la main.",
      "Accrocher le point d'amure du ris à son crochet.",
      "Border la ligne de ris pour ramener le point d'écoute vers la bôme.",
      "Retendre la drisse, puis reborder l'écoute au réglage adapté.",
    ],
    explication: "Choquer avant de descendre, accrocher l'amure, border la ligne de ris, puis retendre : dans cet ordre, sinon la voile reste sous tension et le ris devient difficile à prendre.",
  },
  {
    id: "qz-communication-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-communication-equipage"],
    enonce: "N'importe quel équipier peut dire « Attends ! » pour stopper une manœuvre avant qu'elle ne commence.",
    reponse: true,
    explication: "Le cycle annonce → confirmation → action permet à chacun d'interrompre la manœuvre avant que l'action ne soit déclenchée.",
  },
  {
    id: "qz-carte-marine-qcm",
    type: "qcm",
    conceptIds: ["c-carte-marine"],
    enonce: "Une zone de la carte est teintée différemment près de ta route. Que dois-tu penser ?",
    options: ["C'est un défaut d'impression, sans importance", "C'est souvent le signe d'un danger (roches, hauts-fonds)", "Cela indique toujours un mouillage autorisé", "Cela signale la présence d'un port"],
    reponseIndex: 1,
    explication: "Une teinte différente sur une carte marine signale souvent une zone de danger : il ne faut jamais l'ignorer.",
  },
  {
    id: "qz-derive-qcm",
    type: "qcm",
    conceptIds: ["c-derive-navigation"],
    enonce: "Comment corriger sa route pour compenser une dérive constante due au courant ?",
    options: ["Ne rien faire, le bateau se corrige seul", "Pointer le cap légèrement en amont de la direction voulue", "Accélérer au moteur", "Changer d'allure"],
    reponseIndex: 1,
    explication: "Pointer le cap légèrement en amont de la direction voulue compense la dérive causée par le vent et le courant.",
  },
  {
    id: "qz-maree-courant-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-maree-courant"],
    enonce: "La profondeur et le courant à un mouillage peuvent varier fortement au cours d'une même journée, à cause de la marée.",
    reponse: true,
    explication: "La marée fait varier la hauteur d'eau et génère des courants, deux éléments à surveiller pour un mouillage sûr.",
  },
  {
    id: "qz-coefficient-qcm",
    type: "qcm",
    conceptIds: ["c-marnage-coefficient"],
    enonce: "Un coefficient de marée proche de 100 correspond à...",
    options: ["Une morte-eau, marnage réduit", "Une grande marée, fort marnage", "Une marée sans aucun courant", "Une erreur de mesure"],
    reponseIndex: 1,
    explication: "Un coefficient élevé (au-delà de 90-95 environ) signale une grande marée : fort marnage et courants plus soutenus.",
  },
  {
    id: "qz-douziemes-qcm",
    type: "qcm",
    conceptIds: ["c-douziemes"],
    enonce: "Le marnage est de 4,80 m. Que vaut un douzième ?",
    options: ["0,40 m", "4,80 m", "1,20 m", "0,48 m"],
    reponseIndex: 0,
    explication: "Un douzième = marnage ÷ 12, soit 4,80 ÷ 12 = 0,40 m.",
  },
  {
    id: "qz-etale-scenario",
    type: "scenario",
    conceptIds: ["c-courant-maree"],
    situation: "Tu dois franchir un passage réputé pour ses forts courants de marée, comme le Raz de Sein.",
    options: ["À n'importe quel moment, si le bateau est assez puissant", "À l'étale, quand le courant s'annule presque", "Uniquement à marée haute, quelle que soit l'heure", "Uniquement de nuit"],
    reponseIndex: 1,
    explication: "Passer à l'étale évite de lutter contre plusieurs nœuds de courant contraire — bien plus sûr dans un passage réputé difficile.",
  },
  {
    id: "qz-lire-ciel-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-lire-le-ciel"],
    enonce: "Un ciel qui se charge de nuages bas et sombres à l'ouest annonce souvent une dégradation proche.",
    reponse: true,
    explication: "C'est un signe classique à surveiller, en particulier dans le sens du vent dominant.",
  },
  {
    id: "qz-bulletin-meteo-qcm",
    type: "qcm",
    conceptIds: ["c-bulletin-meteo"],
    enonce: "Que doit-on vérifier dans un bulletin météo marine, en plus de la force et de la direction du vent ?",
    options: ["Uniquement la température de l'air", "L'état de la mer annoncé et les avis de coup de vent", "Le nombre de bateaux au port", "Rien d'autre n'est utile"],
    reponseIndex: 1,
    explication: "Un bulletin météo marine donne aussi l'état de la mer et les avis de coup de vent ou alertes en cours.",
  },
  {
    id: "qz-equipement-securite-vrai-faux",
    type: "vrai-faux",
    conceptIds: ["c-equipement-securite"],
    enonce: "Le port du gilet de sauvetage est optionnel dès que la météo semble calme.",
    reponse: false,
    explication: "Les consignes du bord priment : ce n'est pas parce que la météo semble calme que le port du gilet devient optionnel.",
  },
  {
    id: "qz-ordre-mayday",
    type: "ordre-etapes",
    conceptIds: ["c-alerte-vhf"],
    titre: "Structure d'un appel Mayday",
    etapes: [
      "« Mayday, Mayday, Mayday »",
      "Nom du bateau, répété",
      "Position (coordonnées ou repère connu)",
      "Nature de la détresse et assistance demandée",
      "Nombre de personnes à bord",
    ],
    explication: "Cette structure permet aux secours de comprendre immédiatement qui appelle, où, pour quoi, et combien de personnes sont concernées.",
  },
];

export function getQuizItemsByConcepts(conceptIds: string[]): QuizItem[] {
  const set = new Set(conceptIds);
  return quizItems.filter((q) => q.conceptIds.some((c) => set.has(c)));
}
